version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=nojminoj01
    container_name: postgres
    ports:
      - '5432:5432'
  
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT:-3000}
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: poba@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nojminoj01
    ports:
      - '5050:80'
    depends_on:
      - db