POST http://localhost:3000/auth/reg
Content-Type: application/json

{
  "username": "FandomFlame",
  "password": "teszt123",
  "unas_api": "883249f951f44413734f39b6fa75ae1671475115"
}
###

POST http://localhost:8080/user/new-api
Content-Type: application/json

{
  "userid": "11",
  "apiKey": "123456"
}
###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "AranyAlma",
  "password": "teszt123"
}